### ISSUE TITLE
Fatal error: undefined is not a function

### ISSUE THREAD

**Issue by bfabec** [senssei/grunt-license-bower#4]
The following license for fullcalendar is causing an exception:
{"type":"MIT","url":"https://github.com/fullcalendar/fullcalendar/blob/master/LICENSE.txt"}

for the following bower component: http://fullcalendar.io/

Fatal error: undefined is not a function
TypeError: undefined is not a function
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\lib\index.js:57:49
    at Array.filter (native)
    at Function._.filter._.select (Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\underscore\underscore.js:172:65)
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\lib\index.js:55:49
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\lib\index.js:144:9
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:142:5
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:263:14
    at asyncMap (Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\node_modules\slide\lib\async-map.js:27:18)
    at next (Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:234:5)
    at Z:\workspace_anaas\software\src\node_modules\grunt-license-bower\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:179:7

**Comment by senssei** [comment]
Hi, 

based on stacktrace it seems that problem lays in 'bower-licence' package which is used as base for this plugin. 

I need to investigate this in the mean time, fell free to sent pull request.
